#! /bin/bash

echo "Calling matlab formatter."

if git rev-parse --verify HEAD >/dev/null 2>&1
then
	against=HEAD
else
	# Initial commit: diff against an empty tree object
	against=$(git hash-object -t tree /dev/null)
fi

# If you want to disable MATLAB formatter, set this variable to true.
disablematlabformatter=$(git config hooks.disablematlabformatter)
echo ${disablematlabformatter}
if [[ "${disablematlabformatter}" == "true" ]]
then
    exit
fi

# Redirect output to stderr.
exec 1>&2

file_diff=0
while read file
do
    if [[ $(git diff --name-only ${file} | wc -l) -ne 0 || -e ${file}.tmp ]]
    then
        echo "Please review ${file}.tmp (if exist) and \"mv ${file}.tmp ${tmp}\", then \"git add ${file}\"."
        exit 1
    fi

    if [[ ${file} =~ [0-9A-Za-z_-]+\.m ]]
    then
        echo "======== Check ${file} ========"
        python formatter/matlab_formatter.py ${file} > ${file}.tmp
    elif [[ ${file} =~ [0-9A-Za-z_-]+\.c 
        || ${file} =~ [0-9A-Za-z_-]+\.h 
        || ${file} =~ [0-9A-Za-z_-]+\.hpp 
        || ${file} =~ [0-9A-Za-z_-]+\.cpp ]]
    then
        echo "======== Check ${file} ========"
        clang-format -style="{BasedOnStyle: llvm, IndentWidth: 4}" ${file} > ${file}.tmp
    fi
    
    if [[ $(diff ${file} ${file}.tmp | wc -l ) -ne 0 ]]
    then
        echo "${file} does not pass. Please review ${file}.tmp."
        file_diff=1
    else
        rm ${file}.tmp
    fi
done <<< $(git diff --cached --relative --name-only --diff-filter=AM )

if [[ ${file_diff} -eq 0 ]]
then
    echo "File is not different. Clear to commit."
else
    echo "File is different. Please review all *.tmp files."
    exit 1
fi

