#! /bin/bash

echo "Calling matlab formatter."

if git rev-parse --verify HEAD >/dev/null 2>&1
then
	against=HEAD
else
	# Initial commit: diff against an empty tree object
	against=$(git hash-object -t tree /dev/null)
fi

# If you want to disable MATLAB formatter, set this variable to true.
disablematlabformatter=$(git config --type=bool hooks.disablematlabformater)
if [[ "${matlabformater}" == "true" ]]
then
    exit
fi

# Redirect output to stderr.
exec 1>&2

file_diff=0
while read file
do
    if [[ ${file} =~ [0-9A-Za-z_-]+\.m ]]
    then
        if [[ $(git diff --name-only ${file} | wc -l) -ne 0 ]]
        then
            echo "Please \"git add ${file}\"."
            exit 1
        fi

        echo "Format ${file}"
        pwd
        python formatter/matlab_formatter.py ${file} > ${file}.tmp
        if [[ $(diff ${file} ${file}.tmp | wc -l ) -ne 0 ]]
        then
            file_diff=1
        fi

        cp ${file}.tmp ${file}
    fi
done <<< $(git diff --cached --relative --name-only --diff-filter=AM )

if [[ ${file_diff} -eq 0 ]]
then
    echo "File is not different. Clear to commit."
else
    echo "File is different. Please review"
    exit 1
fi

